// <auto-generated />
using System;
using HelpDesk.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDesk.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelpDesk.Api.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nome_categoria");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            NomeCategoria = "Hardware"
                        },
                        new
                        {
                            IdCategoria = 2,
                            NomeCategoria = "Software"
                        },
                        new
                        {
                            IdCategoria = 3,
                            NomeCategoria = "Acesso"
                        },
                        new
                        {
                            IdCategoria = 4,
                            NomeCategoria = "Rede"
                        },
                        new
                        {
                            IdCategoria = 5,
                            NomeCategoria = "Sistema"
                        });
                });

            modelBuilder.Entity("HelpDesk.Api.Models.LogAuditoria", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_log");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("acao");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_hora");

                    b.Property<int>("IdUsuarioAfetado")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_afetado");

                    b.Property<int>("IdUsuarioExecutor")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_executor");

                    b.Property<string>("IpOrigem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_origem");

                    b.Property<string>("TabelaAfetada")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tabela_afetada");

                    b.HasKey("IdLog");

                    b.HasIndex("IdUsuarioAfetado");

                    b.HasIndex("IdUsuarioExecutor");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.Setor", b =>
                {
                    b.Property<int>("IdSetor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_setor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSetor"));

                    b.Property<string>("NomeSetor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nome_setor");

                    b.HasKey("IdSetor");

                    b.ToTable("Setores");

                    b.HasData(
                        new
                        {
                            IdSetor = 1,
                            NomeSetor = "Financeiro"
                        },
                        new
                        {
                            IdSetor = 2,
                            NomeSetor = "TI"
                        },
                        new
                        {
                            IdSetor = 3,
                            NomeSetor = "RH"
                        },
                        new
                        {
                            IdSetor = 4,
                            NomeSetor = "Administrativo"
                        });
                });

            modelBuilder.Entity("HelpDesk.Api.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TecnicoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TecnicoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SetorIdSetor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetorIdSetor");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2024, 12, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "kaue@empresa.com",
                            Nome = "Kaue",
                            Perfil = "Analista",
                            SenhaHash = "$2b$10$lZ7kIf6XkTZIXCm6aEBh7eiplH0IZ8IqfTXKpp.sRQdihHK9A5FYO",
                            SetorIdSetor = 1
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2024, 12, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "julia.castro@empresa.com",
                            Nome = "Julia Castro",
                            Perfil = "Analista",
                            SenhaHash = "$2b$10$lZ7kIf6XkTZIXCm6aEBh7eiplH0IZ8IqfTXKpp.sRQdihHK9A5FYO",
                            SetorIdSetor = 1
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2024, 12, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vinicius.wayna@empresa.com",
                            Nome = "Vinicius Wayna",
                            Perfil = "Usuario",
                            SenhaHash = "$2b$10$lZ7kIf6XkTZIXCm6aEBh7eiplH0IZ8IqfTXKpp.sRQdihHK9A5FYO",
                            SetorIdSetor = 3
                        },
                        new
                        {
                            Id = 6,
                            DataCriacao = new DateTime(2024, 12, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "vinicius.macedo@empresa.com",
                            Nome = "Vinicius Macedo",
                            Perfil = "Admin",
                            SenhaHash = "$2b$10$lZ7kIf6XkTZIXCm6aEBh7eiplH0IZ8IqfTXKpp.sRQdihHK9A5FYO",
                            SetorIdSetor = 4
                        },
                        new
                        {
                            Id = 7,
                            DataCriacao = new DateTime(2024, 12, 26, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "irineu.julio@empresa.com",
                            Nome = "Irineu Julio",
                            Perfil = "Usuario",
                            SenhaHash = "$2b$10$lZ7kIf6XkTZIXCm6aEBh7eiplH0IZ8IqfTXKpp.sRQdihHK9A5FYO",
                            SetorIdSetor = 2
                        },
                        new
                        {
                            Id = 8,
                            DataCriacao = new DateTime(2024, 12, 27, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "samuel.nobre@empresa.com",
                            Nome = "Samuel NObRe",
                            Perfil = "Usuario",
                            SenhaHash = "$2b$10$lZ7kIf6XkTZIXCm6aEBh7eiplH0IZ8IqfTXKpp.sRQdihHK9A5FYO",
                            SetorIdSetor = 3
                        });
                });

            modelBuilder.Entity("HelpDesk.Api.Models.LogAuditoria", b =>
                {
                    b.HasOne("HelpDesk.Api.Models.Usuario", "UsuarioAfetado")
                        .WithMany("LogsAfetados")
                        .HasForeignKey("IdUsuarioAfetado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDesk.Api.Models.Usuario", "UsuarioExecutor")
                        .WithMany("LogsExecutados")
                        .HasForeignKey("IdUsuarioExecutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioAfetado");

                    b.Navigation("UsuarioExecutor");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.Ticket", b =>
                {
                    b.HasOne("HelpDesk.Api.Models.Usuario", "Tecnico")
                        .WithMany("TicketsAtribuidos")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HelpDesk.Api.Models.Usuario", "Usuario")
                        .WithMany("TicketsAbertos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tecnico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.Usuario", b =>
                {
                    b.HasOne("HelpDesk.Api.Models.Setor", "Setor")
                        .WithMany("Usuarios")
                        .HasForeignKey("SetorIdSetor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Setor");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.Setor", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("HelpDesk.Api.Models.Usuario", b =>
                {
                    b.Navigation("LogsAfetados");

                    b.Navigation("LogsExecutados");

                    b.Navigation("TicketsAbertos");

                    b.Navigation("TicketsAtribuidos");
                });
#pragma warning restore 612, 618
        }
    }
}
